# Change these first
owner: subject-f # Your GitHub organization or username, where this repository lives
repo: cubari-status-page # The name of this repository

sites:
  - name: Cubari
    url: https://cubari.moe/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (MangaDex)
    url: https://cubari.moe/read/mangadex/d86cf65b-5f6c-437d-a0af-19a31f94ec55/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (NHentai)
    url: https://cubari.moe/read/nhentai/381867/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (MangAdventure)
    url: https://cubari.moe/read/mangadventure/aHR0cHMvYXNzb3J0ZWRzY2Fucy5jb20vdGhlLWlsbGlkYW4tZ2lybA/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (Imgur)
    url: https://cubari.moe/read/imgur/ScqMQxz/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (Gist)
    url: https://cubari.moe/read/gist/OPM/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (MangaKatana)
    url: https://cubari.moe/read/mangakatana/aHR0cHM6Ly9tYW5nYWthdGFuYS5jb20vbWFuZ2EvYm9rdS1uby1rb2tvcm8tbm8teWFiYWkteWF0c3UuMjAwMTMv/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (WeebCentral)
    url: https://cubari.moe/read/weebcentral/01J76XYFYYF2DTKP6CNRJD780X/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (imgbox)
    url: https://cubari.moe/read/imgbox/cUGEkRbdZZ/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (ImageChest)
    url: https://cubari.moe/read/imgchest/o24aepq27lj/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (reddit)
    url: https://cubari.moe/read/reddit/16cj0xv/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (imgBB)
    url: https://cubari.moe/read/imgbb/SQMcSX/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (Dynasty Scans)
    url: https://cubari.moe/read/dynasty/the_engagement_of_the_disgraced_witch_and_the_cross_dressing_princess/?cache_buster=$GITHUB_RUN_NUMBER
  - name: Cubari (Catbox)
    url: https://cubari.moe/read/catbox/r47o8s/?cache_buster=$GITHUB_RUN_NUMBER

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.cubari.moe
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/subject-f/cubarimoe/develop/static_global/cubari_logo.png
  name: Cubari.moe Status
  theme: night
  navbar:
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/wwD2xTbQxe

workflowSchedule:
  graphs: "0 * * * *"
  staticSite: "45 * * * *"
  responseTime: "*/30 * * * *"
  summary: "45 * * * *"
  uptime: "*/5 * * * *"
